 CREATE DATABASE  IF NOT EXISTS `rms`;
USE `rms`;

DROP TABLE IF EXISTS `risk`;

  CREATE TABLE `rms`.`risk` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `name` VARCHAR(64) NOT NULL COMMENT '',
  `content` VARCHAR(255) NOT NULL COMMENT '',
  `probability` VARCHAR(64) NOT NULL COMMENT '',
  `influence` VARCHAR(64) NOT NULL COMMENT '',
  `triggerOrThreshold` VARCHAR(64) NOT NULL COMMENT '',
  `submitter` INT NOT NULL COMMENT '',
  `tracer` INT COMMENT '',
  `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP ,
  `update_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)  COMMENT '');