CREATE DATABASE  IF NOT EXISTS `rms` /*!40100 DEFAULT CHARACTER SET utf8mb4 */;
USE `rms`;

DROP TABLE IF EXISTS `risk_state_trace`;

CREATE TABLE `rms`.`risk_state_trace` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `risk_id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(255) NULL,
  `create_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` DATETIME NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`));